/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as IdCardRouteImport } from './routes/id-card'
import { Route as ServicesGraphicsDesignRouteImport } from './routes/services/graphics-design'
import { Route as ServicesWebDevelopmentRouteImport } from './routes/services/web-development'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const IdCardRoute = IdCardRouteImport.update({
  id: '/id-card',
  path: '/id-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGraphicsDesignRoute = ServicesGraphicsDesignRouteImport.update({
  id: '/services/graphics-design',
  path: '/services/graphics-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebDevelopmentRoute = ServicesWebDevelopmentRouteImport.update({
  id: '/services/web-development',
  path: '/services/web-development',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/id-card': typeof IdCardRoute
  '/services/graphics-design': typeof ServicesGraphicsDesignRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/id-card': typeof IdCardRoute
  '/services/graphics-design': typeof ServicesGraphicsDesignRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/id-card': typeof IdCardRoute
  '/services/graphics-design': typeof ServicesGraphicsDesignRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/features'
    | '/id-card'
    | '/services/graphics-design'
    | '/services/web-development'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/features'
    | '/id-card'
    | '/services/graphics-design'
    | '/services/web-development'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/features'
    | '/id-card'
    | '/services/graphics-design'
    | '/services/web-development'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FeaturesRoute: typeof FeaturesRoute
  IdCardRoute: typeof IdCardRoute
  ServicesGraphicsDesignRoute: typeof ServicesGraphicsDesignRoute
  ServicesWebDevelopmentRoute: typeof ServicesWebDevelopmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/id-card': {
      id: '/id-card'
      path: '/id-card'
      fullPath: '/id-card'
      preLoaderRoute: typeof IdCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/graphics-design': {
      id: '/services/graphics-design'
      path: '/services/graphics-design'
      fullPath: '/services/graphics-design'
      preLoaderRoute: typeof ServicesGraphicsDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-development': {
      id: '/services/web-development'
      path: '/services/web-development'
      fullPath: '/services/web-development'
      preLoaderRoute: typeof ServicesWebDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FeaturesRoute: FeaturesRoute,
  IdCardRoute: IdCardRoute,
  ServicesGraphicsDesignRoute: ServicesGraphicsDesignRoute,
  ServicesWebDevelopmentRoute: ServicesWebDevelopmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
